development:
  adapter: postgresql
  encoding: unicode
  database: rubyjobs_development
  pool: 5
  username:
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: rubyjobs_test
  pool: 5
  username:
  password:
  template: template0
